# Generated by Django 3.1 on 2020-08-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('processor', models.CharField(max_length=10)),
                ('CPU', models.CharField(max_length=10)),
                ('Speed', models.IntegerField()),
                ('Gen', models.IntegerField()),
                ('RAM', models.IntegerField()),
                ('Harddrive', models.CharField(max_length=10)),
                ('Camera', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('Battery', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('serial_number', models.CharField(max_length=100)),
                ('customer', models.CharField(max_length=200)),
                ('comments', models.CharField(default='No comments', max_length=200)),
                ('condition', models.CharField(default='Good', max_length=200)),
                ('vendor', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Available', 'Item is available!'), ('Sold', 'Item is sold!')], max_length=25)),
            ],
        ),
    ]
