# Generated by Django 3.1 on 2020-08-11 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptops',
            name='status',
            field=models.CharField(choices=[('Available', 'Item is available'), ('Sold', 'Item is sold')], max_length=25),
        ),
    ]
