# Generated by Django 3.1 on 2020-08-12 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200811_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptops',
            name='CPU',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='laptops',
            name='Speed',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='laptops',
            name='processor',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
