# Generated by Django 3.1 on 2020-08-16 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200815_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptops',
            name='Gen',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='laptops',
            name='RAM',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='laptops',
            name='Speed',
            field=models.CharField(max_length=10),
        ),
    ]
